
TOP=../..

include $(TOP)/configure/CONFIG

PROD_NAME = imagetest
DBD_PREFIX = ioc imagetest
PROD_IOC = $(PROD_NAME)

$(PROD_NAME)_SRCS  +=  main.cpp
$(PROD_NAME)_LIBS += TinyTIFF_Release
#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

