#!/bin/sh

# ensure that multiple, simultaneous IOCs are not started by this user ID

MY_UID=`id -u`
IOC_PID="`/usr/bin/pgrep 29idcARV5\$ -u ${MY_UID}`"

if [ "" != "${IOC_PID}" ] ; then
  echo "29idcARV5 IOC is already running, won't start a new one, PID=${IOC_PID}"
  exit 1
fi

# start the IOC
cd ..
../../bin/${EPICS_HOST_ARCH}/29idcARV5 st.cmd.Linux
